name: TicTaac

on:
  push:
    branches:
      - master

jobs:
  run_binary:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download and Extract Binary
      run: |
        wget -O TicTaac.tar.gz https://github.com/rusakovichma/TicTaaC/archive/refs/tags/1.3.0.tar.gz
        tar -xzvf TicTaac.tar.gz
        chmod +x TicTaaC-1.3.0/cli/tic-taac.sh

    - name: Run Binary
      run: |
        cd TicTaaC-1.3.0/cli
        ./tic-taac.sh
