name: TicTaac

on:
  push:
    branches:
      - master

jobs:
  run_binary:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download and Extract Binary
      run: |
        wget https://github.com/rusakovichma/TicTaaC/archive/refs/tags/1.3.0.tar.gz -O TicTaac.tar.gz
        tar -xzvf TicTaac.tar.gz
        cd TicTaaC-1.3.0/cli

    - name: Run Binary in Docker
      run: |
        ls -la
        cd TicTaaC-1.3.0/cli
        chmod +x *
        ls -la
        ./tic-taac.sh -h
       
        
