name: TicTaac

on:
  push:
    branches:
      - master

jobs:
  run_binary:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download and Extract Binary
      run: |
        wget https://github.com/rusakovichma/TicTaaC/archive/refs/tags/1.3.0.tar.gz -O TicTaac.tar.gz
        tar -xzvf TicTaac.tar.gz
        cd TicTaaC-1.3.0/cli

    - name: Run Binary in Docker
      run: |
        # Install WSL (Ubuntu) and use it to run the Linux commands
        wsl ls -la
        wsl pwd
        wsl cd TicTaaC-1.3.0/cli
        wsl chmod +x *
        wsl ls -la
        wsl ./tic-taac.sh --out . --threatModel /mnt/c/Users/runner/work/TicTaac/TicTaac/CoffeeShopAdvanced-threat-model.yml --format html
