name: TicTaac 

on:
  push:
    branches:
      - master

jobs:
  run_binary:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download and Extract Binary
      run: |
        # Replace the URL and binary name with your actual values
        wget https://github.com/rusakovichma/TicTaaC/archive/refs/tags/1.3.0.tar.gz -o TicTaac
        tar -xzvf TicTaaC
        chmod +x TicTaaC

    - name: Run Binary
      run: TicTaaC
