name: TicTaac

on:
  push:
    branches:
      - master

jobs:
  run_binary:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download and Extract Binary
      run: |
        Invoke-WebRequest -Uri 'https://github.com/rusakovichma/TicTaaC/archive/refs/tags/1.3.0.tar.gz' -OutFile 'TicTaac.tar.gz'
        tar -xzf TicTaac.tar.gz
        Set-Location -Path 'TicTaaC-1.3.0\cli'

    - name: Run Binary in Docker
      run: |
        Get-ChildItem | Format-Table -AutoSize
        Get-Location
        Set-Location -Path 'TicTaaC-1.3.0\cli'
        Get-ChildItem | ForEach-Object { $_.IsReadOnly = $false }
        .\tic-taac.sh --out . --threatModel "${Env:USERPROFILE}\work\TicTaac\TicTaac\CoffeeShopAdvanced-threat-model.yml" --format html

    - name: Archive HTML reports
      uses: actions/upload-artifact@v2
      with:
        name: html-reports
        path: .\report\
