name: TicTaac

on:
  push:
    branches:
      - master

jobs:
  run_binary:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download and Extract Binary
      run: |
        # Corrected the 'wget' command to use -O for output file
        wget https://github.com/rusakovichma/TicTaaC/archive/refs/tags/1.3.0.tar.gz -O TicTaac.tar.gz
        tar -xzvf TicTaac.tar.gz
        chmod +x TicTaaC

    - name: Run Binary
      run: ./TicTaaC
