name: Run TicTaaC

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download and unzip TicTaaC
      run: |
        wget -O tictaac.zip https://github.com/rusakovichma/TicTaaC/releases/latest/download/tic-taac-1.3.0-release.zip
        unzip tictaac.zip -d tictaac
    
    - name: Install dos2unix
      run: sudo apt-get install dos2unix


    - name: Run TicTaaC
      run: |
        pwd
        chmod +x /tictaac/tic-taac/bin/*
        pwd
        ls -la
        dos2unix ./tic-taac.sh
        ./tictaac/tic-taac/bin/tic-taac.sh --out . --threatModel TicTaac\Threat\CoffeeShopAdvanced-threat-model.yml
        ls -la

