name: Run TicTaaC

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download and unzip TicTaaC
      run: |
        wget -O tictaac.zip https://github.com/rusakovichma/TicTaaC/releases/latest/download/tic-taac-1.3.0-release.zip
        unzip tictaac.zip -d tictaac
    
    - name: Install dos2unix
      run: sudo apt-get install dos2unix


    - name: Run TicTaaC
      run: |
        pwd
        mkdir Reports
        cd tictaac/tic-taac/bin
        chmod +x *
        pwd
        ls -la 
        dos2unix ./tic-taac.sh
        ./tic-taac.sh --out /home/runner/work/TicTaac/TicTaac/Reports --threatModel /home/runner/work/TicTaac/TicTaac/Threat/
        ls -la
    
    - name: Upload Reports folder as artifact
      uses: actions/upload-artifact@v2
      with:
        name: Tic-Taac-reports
        path: TicTaac/TicTaac/Reports
        

