name: TicTaac

on:
  push:
    branches:
      - master

jobs:
  run_binary:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download and Extract Binary
      run: |
        wget https://github.com/rusakovichma/TicTaaC/archive/refs/tags/1.3.0.tar.gz -O TicTaac.tar.gz
        tar -xzvf TicTaac.tar.gz
        cd TicTaaC-1.3.0/cli

    - name: Run Binary in Docker
      run: |
        TT_VERSION="latest"
        THREAT_MODEL_DIR=$HOME/threat-model

        # Make sure we are using the latest version
        docker pull rusakovichma/tic-taac:$TT_VERSION

        # Run the Docker container
        docker run --rm \
          -e user=$USER \
          -u $(id -u ${USER}):$(id -g ${USER}) \
          --volume $THREAT_MODEL_DIR:/threat-model:z \
          --volume $(pwd)/report:/report:z \
          rusakovichma/tic-taac:$TT_VERSION \
          /bin/bash -c "cd /threat-model && sh /report"
