name: Run TicTaaC

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download and unzip TicTaaC
      run: |
        wget -O tictaac.zip https://github.com/rusakovichma/TicTaaC/releases/latest/download/tic-taac-1.3.0-release.zip
        unzip tictaac.zip -d tictaac

    - name: Run TicTaaC
      run: |
        cd tictaac/tic-taac/bin
        chmod +x *
        pwd
        ls -la
        ./tic-taac.sh

