name: TicTaac

on:
  push:
    branches:
      - master

jobs:
  run_binary:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download and Extract Binary
      run: |
        TT_VERSION="latest"
        THREAT_MODEL_DIR=$HOME/threat-model

        # Make sure we are using the latest version
        docker pull rusakovichma/tic-taac:$TT_VERSION

        docker run --rm \
          -e user=$USER \
          -u $(id -u ${USER}):$(id -g ${USER}) \
          --volume $THREAT_MODEL_DIR:/threat-model:z \
          --volume $(pwd)/report:/report:z \
          rusakovichma/tic-taac:$TT_VERSION \
          --threatModel /threat-model \
          --outFormat html \
          --out /report
